name: Publish Docker Image

on:
  push:
    branches: master
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 4 * * *"

jobs:
  multi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Get overture latest version
        id: latest_version
        run: |
          sudo apt install jq
          version=$(curl -LSs https://api.github.com/repos/shawn1m/overture/releases | jq -r .[0].tag_name )
          version=$(echo ${version##v})
          echo "::set-output name=result::${version}"
      - name: Get overture latest release version
        id: latest_release_version
        run: |
          sudo apt install jq
          version=$(curl -LSs https://api.github.com/repos/shawn1m/overture/releases | jq -r '[.[] | select(.prerelease==false)] | first | .tag_name')
          version=$(echo ${version##v})
          echo "::set-output name=result::${version}"
      - name: Check whether the latest version is prerelease
        id: the_latest_is_prerelease
        run: |
          latest_version=${{ steps.latest_version.outputs.result }}
          latest_release_version=${{ steps.latest_release_version.outputs.result }}
          the_latest_is_prerelease=1
          if [ "$latest_version" = "$latest_release_version" ]; then the_latest_is_prerelease=0; fi
          echo "::set-output name=result::${the_latest_is_prerelease}"
      - name: Set docker image tags
        id: docker_tags
        run: |
          latest_version=${{ steps.latest_version.outputs.result }}
          special_version=${{ secrets.VERSION }}
          version=${special_version:-$latest_version}
          version_tags="${{ secrets.DOCKERHUB_USERNAME }}/overture:$version,ghcr.io/${{ github.actor }}/overture:$version"
          tags_with_latest="$version_tags,${{ secrets.DOCKERHUB_USERNAME }}/overture:latest,ghcr.io/${{ github.actor }}/overture:latest"
          tags=$version_tags
          if [ -z "$special_version" ] || [ "$latest_version" == "$special_version" ]; then tags=$tags_with_latest; fi
          echo "::set-output name=result::${tags}"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm64,arm
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      # Setup the Github Actions cache.
      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildxarch-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildxarch-
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to Github Package
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: $GITHUB_ACTOR
          password: ${{ secrets.PACKAGE_TOKEN }}
      # the arm64 is of course much slower due to qemu, so build and push amd64 **first**
      # due to the way manifests work, the gap between this and the complete push below
      #  could result in pull failures or inconsistencies for arm64, such is life.
      # further duplicated by building both release and debug builds
      - name: Build and push amd64 Release Docker Image to DockerHub and Github docker registry
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_tags.outputs.result }}
          build-args: |
            VERSION=${{ secrets.VERSION }}
            PRERELEASE=1
          cache-from: type=local,src=/tmp/.buildx-cache
          # first run does not export the cache

      # Do it all again with both archs. the amd64 will be a huge cache hit
      # this will update the manifest have both arches
      - name: Build and push multiarch Release Docker Image to DockerHub and Github docker registry
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/arm64,linux/arm/v7,linux/amd64
          push: true
          tags: ${{ steps.docker_tags.outputs.result }}
          build-args: |
            VERSION=${{ secrets.VERSION }}
            PRERELEASE=1
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      # Build latest non-prerelease
      - name: Build and push amd64 Non-PreRelease Docker Image to DockerHub and Github docker registry
        if: steps.the_latest_is_prerelease.outputs.result == 1
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/overture:${{ steps.latest_release_version.outputs.result }}
            ghcr.io/${{ github.actor }}/overture:${{ steps.latest_release_version.outputs.result }}
          build-args: |
            VERSION=${{ steps.latest_release_version.outputs.result }}
          cache-from: type=local,src=/tmp/.buildx-cache-release
          # first run does not export the cache

      # Do it all again with both archs. the amd64 will be a huge cache hit
      # this will update the manifest have both arches
      - name: Build and push multiarch Non-PreRelease Docker Image to DockerHub and Github docker registry
        if: steps.the_latest_is_prerelease.outputs.result == 1
        uses: docker/build-push-action@v2
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Dockerfile
          platforms: linux/arm64,linux/arm/v7,linux/amd64
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/overture:${{ steps.latest_release_version.outputs.result }}
            ghcr.io/${{ github.actor }}/overture:${{ steps.latest_release_version.outputs.result }}
          build-args: |
            VERSION=${{ steps.latest_release_version.outputs.result }}
          cache-from: type=local,src=/tmp/.buildx-cache-release
          cache-to: type=local,dest=/tmp/.buildx-cache-release
